{
 "title": "Market Data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "grafana-clickhouse-datasource" },
   {
    "name": "Ticker",
    "query": "SELECT DISTINCT symbol\nFROM minute_bars_final\nORDER BY symbol"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Price - ${Ticker}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    minute,\r\n    open\r\nFROM minute_bars_final\r\nWHERE symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\nORDER BY minute DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Price - ${Ticker}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    minute,\r\n    open, \r\n    symbol\r\nFROM minute_bars_final\r\nWHERE symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\nORDER BY minute DESC"
    }
   ]
  },
  {
   "title": "Trading Volume - ${Ticker}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume) AS total_vol\r\nFROM minute_bars_final\r\nWHERE symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\n"
    }
   ]
  },
  {
   "title": "Notional Volume - ${Ticker}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume * open) AS total_vol_usd\r\nFROM minute_bars_final\r\nWHERE $__timeFilter(minute) AND symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\n\r\n"
    }
   ]
  },
  {
   "title": "Trading Volume - ${Ticker}",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    minute,\r\n    volume\r\nFROM minute_bars_final\r\nWHERE symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\nORDER BY minute DESC"
    }
   ]
  }
 ]
}