{
 "title": "Server Monitoring",
 "description": "Monitors the Kafka producer",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "nodename",
    "label": "Nodename",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", nodename=\"$nodename\"},instance)"
    }
   },
   { "name": "ds_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Server Up Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds{job=~\"$job\"} - node_boot_time_seconds{job=~\"$job\"})\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "Overall Disk Space used",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum by (job) (node_filesystem_size_bytes{job=~\"$job\", device!~\"rootfs\"})\r\n  - sum by (job) (node_filesystem_avail_bytes{job=~\"$job\", device!~\"rootfs\"})\r\n)\r\n/\r\nsum by (job) (node_filesystem_size_bytes{job=~\"$job\", device!~\"rootfs\"}) * 100\r\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Busy",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (job) (\r\n  node_memory_MemAvailable_bytes{job=~\"$job\"}\r\n) / avg by (job) (\r\n  node_memory_MemTotal_bytes{job=~\"$job\"}\r\n))\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}